<?php
/**
 * @file
 * Install file for commerce_migrate_ubercart_shipping.
 */

/**
 * Implements hook_uninstall().
 * to deregister migrations.
 */
function commerce_migrate_physical_product_uninstall() {
  $migrations = array(
    'CommerceMigratePhysicalProduct',
  );
  module_load_include('module', 'commerce_migrate_ubercart');
  foreach ($migrations as $migration) {
    Migration::deregisterMigration($migration);
  }
}